#!/bin/bash
# Export a MySQL database table into CSV format
#
# Usage: mysqltocsv <host> <user> <pass> <database> <table> [fields] [header] [separator] [endline] [enclose] [escape] [endline];
#
# If fields is omitted '*' is assumed
# Default separator ';'

HOST="$1"
USER="$2"
PASS="$3"
DATABASE="$4"
TABLE="$5"
FIELDS="$6"
HEADER="$7"
SEPARATOR="$8"
ENCLOSE="$9"
ESCAPE="${10}"
ENDLINE="${11}"

if [ -z "$HOST" ]; then
    echo "Host is mandatory"
	echo "Usage: mysqltocsv  <host> <user> <pass> <database> <table> [fields] [header] [separator] [endline] [enclose] [escape] [endline]"
	exit 1
fi

if [ -z "$USER" ]; then
    echo "User is mandatory"
	echo "Usage: mysqltocsv <host> <user> <pass> <database> <table> [fields] [header] [separator] [endline] [enclose] [escape] [endline]"
	exit 1
fi

if [ -z "$PASS" ]; then
    echo "Password is mandatory"
	echo "Usage: mysqltocsv <host> <user> <pass> <database> <table> [fields] [header] [separator] [endline] [enclose] [escape] [endline]"
	exit 1
fi

if [ -z "$DATABASE" ]; then
    echo "Database is mandatory"
	echo "Usage: mysqltocsv <host> <user> <pass> <database> <table> [fields] [header] [separator] [endline] [enclose] [escape] [endline]"
	exit 1
fi

if [ -z "$TABLE" ]; then
	echo "Table name missing"
	exit 1
fi

if [ -z "$FIELDS" ]; then
	FIELDS='*'
fi

if [ -z "$SEPARATOR" ]; then
	SEPARATOR=';'
fi

#Verify mysql variables 'secure_file_priv'
#mysql -e SHOW VARIABLES LIKE "secure_file_priv"
TMP=`mktemp -p /var/lib/mysql-files -u mysql-csv.XXXXXX`

QUERY="SELECT $FIELDS FROM $TABLE INTO OUTFILE '$TMP' FIELDS TERMINATED BY '$SEPARATOR' ENCLOSED BY '$ENCLOSE' ESCAPED BY '$ESCAPE' LINES TERMINATED BY '$ENDLINE'"

if [ -n "$HEADER" ]; then
    QUERY="(SELECT $HEADER) UNION (${QUERY})"
fi

mysql --host="$HOST" --user="$USER" --password="$PASS" --database="$DATABASE" --execute="${QUERY}"

cat "$TMP"
rm "$TMP"

exit 0

